<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="MailKit" Version="4.5.0" />
    <PackageReference Include="Mustache.NETStandard" Version="1.1.0" />
    <PackageReference Include="Keycloak.AuthServices.Authentication" Version="1.6.0" />
    <PackageReference Include="Keycloak.AuthServices.Authorization" Version="1.6.0" />
    <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
    <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.3" />
    <PackageReference Include="Serilog" Version="3.1.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankingSystem.MessageBrokers.Shared\BankingSystem.MessageBrokers.Shared.csproj" />
    <ProjectReference Include="..\BankingSystem.Messages.Shared\BankingSystem.Messages.Shared.csproj" />
  </ItemGroup>

</Project>
